//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int User_ID { get; set; }
        public string Picture { get; set; }
        public string Full_Name { get; set; }
        public string Father_Name { get; set; }
        public string NIC { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Contact_Number { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UserRole { get; set; }
    }
}
