//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int U_Id { get; set; }
        public int Package_ID { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public System.DateTime DOB { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Contact_Number { get; set; }
        public string Transaction_Id { get; set; }
        public string Hotel_Id { get; set; }
        public Nullable<bool> isReviewed { get; set; }
        public string QRCode { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
