//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiderReview
    {
        public int Id { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Review { get; set; }
        public string Email { get; set; }
        public Nullable<int> Guider_ID { get; set; }
    
        public virtual TourGuider TourGuider { get; set; }
    }
}
