//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public string Details { get; set; }
        public int Rating { get; set; }
        public int City_Id { get; set; }
        public int Rooms { get; set; }
        public int Available_Rooms { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual City City { get; set; }
    }
}
