//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoreToIt_DatabaseEntities : DbContext
    {
        public MoreToIt_DatabaseEntities()
            : base("name=MoreToIt_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<City> Citys { get; set; }
        public virtual DbSet<FamousPlace> FamousPlaces { get; set; }
        public virtual DbSet<GuiderReview> GuiderReviews { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<PackageReview> PackageReviews { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PickUpLocation> PickUpLocations { get; set; }
        public virtual DbSet<TourGuider> TourGuiders { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleReview> VehicleReviews { get; set; }
    }
}
