//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Bookings = new HashSet<Booking>();
            this.PackageReviews = new HashSet<PackageReview>();
        }
    
        public int Package_ID { get; set; }
        public string Picture { get; set; }
        public string Name { get; set; }
        public string Pick_Up_Location { get; set; }
        public string No_of_Days { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Cities { get; set; }
        public string Places { get; set; }
        public string TripDays { get; set; }
        public string Hotels { get; set; }
        public string Inclusions { get; set; }
        public string Exclusions { get; set; }
        public Nullable<int> No_of_Bookings { get; set; }
        public Nullable<int> Total_Seats { get; set; }
        public Nullable<bool> IsCustomize { get; set; }
        public Nullable<int> GuiderID { get; set; }
        public Nullable<int> VehicleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageReview> PackageReviews { get; set; }
        public virtual TourGuider TourGuider { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
