//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Packages = new HashSet<Package>();
            this.VehicleReviews = new HashSet<VehicleReview>();
        }
    
        public int Id { get; set; }
        public string User_Name { get; set; }
        public string Phone_No { get; set; }
        public string Vehicle_No { get; set; }
        public string Vehicle_Company { get; set; }
        public string Vehicle_Model { get; set; }
        public int Vehicle_Model_Year { get; set; }
        public int Vehicle_Mileage { get; set; }
        public string Vehicle_Pictures { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Rent { get; set; }
        public string City { get; set; }
        public string Vehicle_Type { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleReview> VehicleReviews { get; set; }
    }
}
